name: ng2_modular_admin
version: 0.0.3
description: Modular Admin for Angular2Dart
authors:
  - Mark E. Haase <mehaase@gmail.com>
homepage: https://github.com/hyperiongray/ng2_modular_admin
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0'
  ng2_fontawesome: '^4.7.0'
dev_dependencies:
  args: '^0.13.0'
  path: '^1.4.0'
transformers:
  - angular2:
      platform_directives:
        - package:angular2/common.dart#COMMON_DIRECTIVES
      platform_pipes:
        - package:angular2/common.dart#COMMON_PIPES
