name: ng_modular_admin
version: 1.0.1
description: >
  Modular Admin for Angular Dart is a Boostrap theme for building web
  applications.
homepage: https://github.com/hyperiongray/ng_modular_admin
authors:
- Mark E. Haase <mehaase@gmail.com>
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: '^6.0.0-alpha'
  angular_forms: any
  angular_router: any
  ng_fontawesome: any
dependency_overrides:
  ng_fontawesome:
    path: ../ng_fontawesome
dev_dependencies:
  build_runner: ^1.5.1
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.2
