name: ng_modular_admin
version: 0.0.5
description: >
  Modular Admin for Angular Dart is a Boostrap theme for building web
  applications.
homepage: https://github.com/hyperiongray/ng_modular_admin
authors:
- Mark E. Haase <mehaase@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: '^4.0.0'
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  ng_fontawesome: '^4.7.0'

dev_dependencies:
  args: '^0.13.0'
  path: '^1.4.0'

transformers:
- angular
